### ISSUE TITLE
[suggestion] Use stream copy instead of rawvideo

### ISSUE THREAD

**Issue by moppman** [Kyuunex/better_droidcam_linux_client#1]
Newer ffmpeg versions (?)  seem to be able to output mjpeg to v4l2.  That means we could use, e.g.
`ffmpeg -i http://127.0.0.1:4747/video?1920x1080 -c:v copy -f v4l2 /dev/video10
`, so that we copy the mjpeg stream from droidcam instead of converting it to rawvideo and changing the pixel format. 
This results in a significantly better performance on my old machine at least.
Thanks!

**Comment by qnxt** [comment]
i will look into this

**Comment by qnxt** [comment]
changed. Thanks! this is much better
